# .github/workflows/ci.yml
name: CI - API Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (generate HTML report)
        run: |
          mkdir -p reports
          pytest --maxfail=1 --disable-warnings -q --html=reports/report.html --self-contained-html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html